[project]
name = "natlangq"
version = "0.1.0"
description = "A natural language query tool"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "google-genai",
    "itsdangerous",
    "python-dotenv",
    "python-multipart",
    "polars>=1.38.1",
    "matplotlib",
    "seaborn",
    "pyarrow",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
